print("bienveunue dans le programme qui te peremret de trouver la plus petite et la plus grande valeur d'une liste")
print("give me one random number")
number1=float (input())
print("now give me another number")
number2=float (input())
print("now give me a final number")
number3=float (input())
print("la plus petite valeur est:"+ str(min(number1,number2,number3)))
print("la plus grande valeur est:"+ str(max(number1,number2,number3)))
