print("hellow what's ur name?")
name=input()
print("eyyyy "+ name)
print("how old are u?")
age=input()
print("u are "+age+" years old")
print("this is weird but where dou live?")
city=input()
print("oh okeyy ur name is "+name+" ur "+age+ " years old and u live in "+city)